### ISSUE TITLE
Create ReadMe.

### ISSUE THREAD

**Issue by vipul-rajput** [vipul-rajput/symp-org#1]
Create a short readme discrimination, explaining about Hacktobrfest, requirement of website (Responsiveness, Animation, fonts, Carousel, etc)

**Comment by abhikhedekar4241** [comment]
I would like to do this.

**Comment by vipul-rajput** [comment]
Sure, I have Assigned you. If you have any doubt comment here. All the best :-)...

**Comment by ghost** [comment]
I would like to contribute please assign

**Comment by vipul-rajput** [comment]
its already completed...
